### ISSUE TITLE
Wrong Bytes to Kilobytes conversion

### ISSUE THREAD

**Issue by andyhot** [vigetlabs/json-weight#1]
It should divide by 1024

https://github.com/vigetlabs/json-weight/blob/master/lib/analyze.js#L7

**Comment by nhunzaker** [comment]
Yeesh, that's embarrassing. Should we upstream this to https://github.com/substack/utf8-length too?

**Comment by nhunzaker** [comment]
Nope. I'm just totally wrong. I'll update this shortly. Good grief.

**Comment by nhunzaker** [comment]
Shipped:

https://github.com/vigetlabs/json-weight/releases/tag/v0.2.0

I apologize for that...
